# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20170315_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
