# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:33
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20170315_1432'),
    ]

    operations = [
    ]
